repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort StatisticsMicroservice/ tests/
        language: system
        types: [python]
        pass_filenames: false

      - id: black
        name: black
        entry: black StatisticsMicroservice/ tests/
        language: system
        types: [python]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 StatisticsMicroservice/ tests/
        language: system
        types: [python]
        pass_filenames: false

      - id: tests
        name: tests
        entry: pytest .
        language: system
        types: [python]
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: mypy StatisticsMicroservice/
        language: system
        types: [python]
        pass_filenames: false
