version: '3.5'

services:
  api:
    build: .
    command: scripts/start.sh
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=db_username
      - POSTGRES_PASSWORD=db_password

    depends_on:
      - postgres

    restart: on-failure

  postgres:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=db_username
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_name
      - LANG=en_US.utf8

    restart: on-failure
